//! This file is generated by [build.rs]. DO NOT MODIFY.

use super::codes::*;
use super::type_flags::*;
use crate::Operation;

pub struct Template {
    pub operation: Operation,
    pub dst: TypeFlags,
    pub src: TypeFlags,
    pub codes: &'static [Code],
}

impl std::fmt::Display for Template {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{} [{}, {}] [{}]",
            self.operation,
            format_type_flags(self.dst),
            format_type_flags(self.src),
            codes_to_string(self.codes),
        )
    }
}

macro_rules! t {
    ($operation:ident, [$($more:expr),+]) => {{
        Template {
            operation: Operation::$operation,
            dst: T_NONE,
            src: T_NONE,
            codes: &[$($more),*],
        }
    }};

    ($operation:ident, $dst:expr, [$($more:expr),+]) => {{
        Template {
            operation: Operation::$operation,
            dst: $dst,
            src: T_NONE,
            codes: &[$($more),*],
        }
    }};

    ($operation:ident, $dst:expr, $src:expr, [$($more:expr),+]) => {{
        Template {
            operation: Operation::$operation,
            dst: $dst,
            src: $src,
            codes: &[$($more),*],
        }
    }};
}
#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_IN: &[Template] = &[
    t!(IN, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0xE4, C_IMM_BYTE]),
    t!(IN, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_8, [C_BYTE, 0xE5, C_IMM_BYTE]),
    t!(IN, T_REG|T_REG_AL_AX|T_BITS_8, T_REG|T_REG_DL_DX|T_BITS_16, [C_BYTE, 0xEC]),
    t!(IN, T_REG|T_REG_AL_AX|T_BITS_16, T_REG|T_REG_DL_DX|T_BITS_16, [C_BYTE, 0xED]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LAHF: &[Template] = &[
    t!(LAHF, [C_BYTE, 0x9F]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LDS: &[Template] = &[
    t!(LDS, T_REG|T_BITS_16, T_MEM_DIR|T_MEM_IND, [C_BYTE, 0xC5, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LEA: &[Template] = &[
    t!(LEA, [C_BYTE, 0x8D, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LES: &[Template] = &[
    t!(LES, [C_BYTE, 0xC4, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_MOV: &[Template] = &[
    t!(MOV, T_REG|T_REG_AL_AX|T_BITS_8, T_MEM_DIR|T_BITS_8, [C_BYTE, 0xA0, C_IMM_WORD]),
    t!(MOV, T_REG|T_REG_AL_AX|T_BITS_16, T_MEM_DIR|T_BITS_16, [C_BYTE, 0xA1, C_IMM_WORD]),
    t!(MOV, T_REG|T_BITS_8, T_IMM|T_BITS_8, [C_REG_BASE, 0xB0, C_IMM_BYTE]),
    t!(MOV, T_REG|T_BITS_16, T_IMM|T_BITS_16, [C_REG_BASE, 0xB8, C_IMM_WORD]),
    t!(MOV, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x8A, C_MOD_REG_RM]),
    t!(MOV, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x8B, C_MOD_REG_RM]),
    t!(MOV, T_SEG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x8E, C_MOD_REG_RM]),
    t!(MOV, T_MEM_DIR|T_BITS_8, T_REG|T_REG_AL_AX|T_BITS_8, [C_BYTE, 0xA2, C_IMM_WORD]),
    t!(MOV, T_MEM_DIR|T_BITS_16, T_REG|T_REG_AL_AX|T_BITS_16, [C_BYTE, 0xA3, C_IMM_WORD]),
    t!(MOV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0xC6, C_MOD_RM, 0x00, C_IMM_BYTE]),
    t!(MOV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0xC7, C_MOD_RM, 0x00, C_IMM_WORD]),
    t!(MOV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x88, C_MOD_REG_RM]),
    t!(MOV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x89, C_MOD_REG_RM]),
    t!(MOV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_SEG|T_BITS_16, [C_BYTE, 0x8C, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_OUT: &[Template] = &[
    t!(OUT, T_IMM|T_BITS_8, T_REG|T_REG_AL_AX|T_BITS_8, [C_BYTE, 0xE6, C_IMM_BYTE]),
    t!(OUT, T_IMM|T_BITS_8, T_REG|T_REG_AL_AX|T_BITS_16, [C_BYTE, 0xE7, C_IMM_BYTE]),
    t!(OUT, T_REG|T_REG_DL_DX|T_BITS_16, T_REG|T_REG_AL_AX|T_BITS_8, [C_BYTE, 0xEE]),
    t!(OUT, T_REG|T_REG_DL_DX|T_BITS_16, T_REG|T_REG_AL_AX|T_BITS_16, [C_BYTE, 0xEF]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_POP: &[Template] = &[
    t!(POP, T_REG|T_BITS_16, [C_REG_BASE, 0x58]),
    t!(POP, T_SEG|T_SEG_DS|T_BITS_16, [C_BYTE, 0x1F]),
    t!(POP, T_SEG|T_SEG_SS|T_BITS_16, [C_BYTE, 0x17]),
    t!(POP, T_SEG|T_SEG_CS|T_BITS_16, [C_BYTE, 0x0F]),
    t!(POP, T_SEG|T_SEG_ES|T_BITS_16, [C_BYTE, 0x07]),
    t!(POP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x8F, C_MOD_RM, 0x00]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_POPF: &[Template] = &[
    t!(POPF, [C_BYTE, 0x9D]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_PUSH: &[Template] = &[
    t!(PUSH, T_REG|T_BITS_16, [C_REG_BASE, 0x50]),
    t!(PUSH, T_SEG|T_SEG_DS|T_BITS_16, [C_BYTE, 0x1E]),
    t!(PUSH, T_SEG|T_SEG_SS|T_BITS_16, [C_BYTE, 0x16]),
    t!(PUSH, T_SEG|T_SEG_CS|T_BITS_16, [C_BYTE, 0x0E]),
    t!(PUSH, T_SEG|T_SEG_ES|T_BITS_16, [C_BYTE, 0x06]),
    t!(PUSH, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x06]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_PUSHF: &[Template] = &[
    t!(PUSHF, [C_BYTE, 0x9C]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SAHF: &[Template] = &[
    t!(SAHF, [C_BYTE, 0x9E]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_XCHG: &[Template] = &[
    t!(XCHG, T_REG|T_REG_AL_AX|T_BITS_16, [C_REG_BASE, 0x90]),
    t!(XCHG, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x86, C_MOD_REG_RM]),
    t!(XCHG, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x87, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_XLAT: &[Template] = &[
    t!(XLAT, [C_BYTE, 0xD7]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_AAA: &[Template] = &[
    t!(AAA, [C_BYTE, 0x37]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_AAD: &[Template] = &[
    t!(AAD, [C_BYTE, 0xD5, C_BYTE, 0x0A]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_AAM: &[Template] = &[
    t!(AAM, [C_BYTE, 0xD4, C_BYTE, 0x0A]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_AAS: &[Template] = &[
    t!(AAS, [C_BYTE, 0x3F]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_ADC: &[Template] = &[
    t!(ADC, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x14, C_IMM_BYTE]),
    t!(ADC, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x15, C_IMM_WORD]),
    t!(ADC, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x12, C_MOD_REG_RM]),
    t!(ADC, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x13, C_MOD_REG_RM]),
    t!(ADC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_SIGNED|T_BITS_8, [C_BYTE, 0x83, C_MOD_RM, 0x02, C_IMM_SIGN_BYTE]),
    t!(ADC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x02, C_IMM_BYTE]),
    t!(ADC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x02, C_IMM_WORD]),
    t!(ADC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x10, C_MOD_REG_RM]),
    t!(ADC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x11, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_ADD: &[Template] = &[
    t!(ADD, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x04, C_IMM_BYTE]),
    t!(ADD, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x05, C_IMM_WORD]),
    t!(ADD, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x02, C_MOD_REG_RM]),
    t!(ADD, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x03, C_MOD_REG_RM]),
    t!(ADD, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_SIGNED|T_BITS_8, [C_BYTE, 0x83, C_MOD_RM, 0x00, C_IMM_SIGN_BYTE]),
    t!(ADD, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x00, C_IMM_BYTE]),
    t!(ADD, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x00, C_IMM_WORD]),
    t!(ADD, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x00, C_MOD_REG_RM]),
    t!(ADD, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x01, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CBW: &[Template] = &[
    t!(CBW, [C_BYTE, 0x98]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CMP: &[Template] = &[
    t!(CMP, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x3C, C_IMM_BYTE]),
    t!(CMP, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x3D, C_IMM_WORD]),
    t!(CMP, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x3A, C_MOD_REG_RM]),
    t!(CMP, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x3B, C_MOD_REG_RM]),
    t!(CMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_SIGNED|T_BITS_8, [C_BYTE, 0x83, C_MOD_RM, 0x07, C_IMM_SIGN_BYTE]),
    t!(CMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x07, C_IMM_BYTE]),
    t!(CMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x07, C_IMM_WORD]),
    t!(CMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x38, C_MOD_REG_RM]),
    t!(CMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x39, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CWD: &[Template] = &[
    t!(CWD, [C_BYTE, 0x99]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_DAA: &[Template] = &[
    t!(DAA, [C_BYTE, 0x27]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_DAS: &[Template] = &[
    t!(DAS, [C_BYTE, 0x2F]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_DEC: &[Template] = &[
    t!(DEC, T_REG|T_BITS_16, [C_REG_BASE, 0x48]),
    t!(DEC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xFE, C_MOD_RM, 0x01]),
    t!(DEC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x01]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_DIV: &[Template] = &[
    t!(DIV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xF6, C_MOD_RM, 0x06]),
    t!(DIV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xF7, C_MOD_RM, 0x06]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_IDIV: &[Template] = &[
    t!(IDIV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xF6, C_MOD_RM, 0x07]),
    t!(IDIV, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xF7, C_MOD_RM, 0x07]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_IMUL: &[Template] = &[
    t!(IMUL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xF6, C_MOD_RM, 0x05]),
    t!(IMUL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xF7, C_MOD_RM, 0x05]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_INC: &[Template] = &[
    t!(INC, T_REG|T_BITS_16, [C_REG_BASE, 0x40]),
    t!(INC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xFE, C_MOD_RM, 0x00]),
    t!(INC, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x00]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_MUL: &[Template] = &[
    t!(MUL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0xF6, C_MOD_RM, 0x04]),
    t!(MUL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xF7, C_MOD_RM, 0x04]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_NEG: &[Template] = &[
    t!(NEG, [C_BYTE, 0xF6, C_MOD_RM, 0x03]),
    t!(NEG, [C_BYTE, 0xF7, C_MOD_RM, 0x03]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SBB: &[Template] = &[
    t!(SBB, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x0E, C_IMM_BYTE]),
    t!(SBB, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x0F, C_IMM_WORD]),
    t!(SBB, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x1A, C_MOD_REG_RM]),
    t!(SBB, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x1B, C_MOD_REG_RM]),
    t!(SBB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_SIGNED|T_BITS_8, [C_BYTE, 0x83, C_MOD_RM, 0x03, C_IMM_SIGN_BYTE]),
    t!(SBB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x03, C_IMM_BYTE]),
    t!(SBB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x03, C_IMM_WORD]),
    t!(SBB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x18, C_MOD_REG_RM]),
    t!(SBB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x19, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SUB: &[Template] = &[
    t!(SUB, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x2C, C_IMM_BYTE]),
    t!(SUB, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x2D, C_IMM_WORD]),
    t!(SUB, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x2A, C_MOD_REG_RM]),
    t!(SUB, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x2B, C_MOD_REG_RM]),
    t!(SUB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_SIGNED|T_BITS_8, [C_BYTE, 0x83, C_MOD_RM, 0x05, C_IMM_SIGN_BYTE]),
    t!(SUB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x05, C_IMM_BYTE]),
    t!(SUB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x05, C_IMM_WORD]),
    t!(SUB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x28, C_MOD_REG_RM]),
    t!(SUB, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x29, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_AND: &[Template] = &[
    t!(AND, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x24, C_IMM_BYTE]),
    t!(AND, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x25, C_IMM_WORD]),
    t!(AND, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x22, C_MOD_REG_RM]),
    t!(AND, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x23, C_MOD_REG_RM]),
    t!(AND, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x04, C_IMM_BYTE]),
    t!(AND, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x04, C_IMM_WORD]),
    t!(AND, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x20, C_MOD_REG_RM]),
    t!(AND, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x21, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_NOT: &[Template] = &[
    t!(NOT, [C_BYTE, 0xF6, C_MOD_RM, 0x02]),
    t!(NOT, [C_BYTE, 0xF7, C_MOD_RM, 0x02]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_OR: &[Template] = &[
    t!(OR, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x0C, C_IMM_BYTE]),
    t!(OR, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x0D, C_IMM_WORD]),
    t!(OR, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x0A, C_MOD_REG_RM]),
    t!(OR, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x0B, C_MOD_REG_RM]),
    t!(OR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x01, C_IMM_BYTE]),
    t!(OR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x01, C_IMM_WORD]),
    t!(OR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x08, C_MOD_REG_RM]),
    t!(OR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x09, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_RCL: &[Template] = &[
    t!(RCL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x02]),
    t!(RCL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x02]),
    t!(RCL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x02]),
    t!(RCL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x02]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_RCR: &[Template] = &[
    t!(RCR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x03]),
    t!(RCR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x03]),
    t!(RCR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x03]),
    t!(RCR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x03]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_ROL: &[Template] = &[
    t!(ROL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x00]),
    t!(ROL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x00]),
    t!(ROL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x00]),
    t!(ROL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x00]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_ROR: &[Template] = &[
    t!(ROR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x01]),
    t!(ROR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x01]),
    t!(ROR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x01]),
    t!(ROR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x01]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SAR: &[Template] = &[
    t!(SAR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x07]),
    t!(SAR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x07]),
    t!(SAR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x07]),
    t!(SAR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x07]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SHL: &[Template] = &[
    t!(SHL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x04]),
    t!(SHL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x04]),
    t!(SHL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x04]),
    t!(SHL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x04]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SHR: &[Template] = &[
    t!(SHR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD0, C_MOD_RM, 0x05]),
    t!(SHR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_ONE|T_BITS_8, [C_BYTE, 0xD1, C_MOD_RM, 0x05]),
    t!(SHR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD2, C_MOD_RM, 0x05]),
    t!(SHR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_REG_CL_CX|T_BITS_8, [C_BYTE, 0xD3, C_MOD_RM, 0x05]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_TEST: &[Template] = &[
    t!(TEST, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0xA8, C_IMM_BYTE]),
    t!(TEST, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0xA9, C_IMM_WORD]),
    t!(TEST, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x84, C_MOD_REG_RM]),
    t!(TEST, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x85, C_MOD_REG_RM]),
    t!(TEST, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0xF6, C_MOD_RM, 0x00, C_IMM_BYTE]),
    t!(TEST, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0xF7, C_MOD_RM, 0x00, C_IMM_WORD]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_XOR: &[Template] = &[
    t!(XOR, T_REG|T_REG_AL_AX|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x34, C_IMM_BYTE]),
    t!(XOR, T_REG|T_REG_AL_AX|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x35, C_IMM_WORD]),
    t!(XOR, T_REG|T_BITS_8, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, [C_BYTE, 0x32, C_MOD_REG_RM]),
    t!(XOR, T_REG|T_BITS_16, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0x33, C_MOD_REG_RM]),
    t!(XOR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_IMM|T_BITS_8, [C_BYTE, 0x80, C_MOD_RM, 0x06, C_IMM_BYTE]),
    t!(XOR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_IMM|T_BITS_16, [C_BYTE, 0x81, C_MOD_RM, 0x06, C_IMM_WORD]),
    t!(XOR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_8, T_REG|T_BITS_8, [C_BYTE, 0x30, C_MOD_REG_RM]),
    t!(XOR, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, T_REG|T_BITS_16, [C_BYTE, 0x31, C_MOD_REG_RM]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CMPS: &[Template] = &[
    t!(CMPSB, [C_BYTE, 0xA6]),
    t!(CMPSW, [C_BYTE, 0xA7]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LODS: &[Template] = &[
    t!(LODSB, [C_BYTE, 0xAC]),
    t!(LODSW, [C_BYTE, 0xAD]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_MOVS: &[Template] = &[
    t!(MOVSB, [C_BYTE, 0xA4]),
    t!(MOVSW, [C_BYTE, 0xA5]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_REP: &[Template] = &[
    t!(REP, [C_BYTE, 0xF2]),
    t!(REPNE, [C_BYTE, 0xF3]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_SCAS: &[Template] = &[
    t!(SCASB, [C_BYTE, 0xAE]),
    t!(SCASW, [C_BYTE, 0xAF]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_STOS: &[Template] = &[
    t!(STOSB, [C_BYTE, 0xAA]),
    t!(STOSW, [C_BYTE, 0xAB]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CALL: &[Template] = &[
    t!(CALL, T_IMM|T_BITS_16, [C_BYTE, 0xE8, C_DISP_WORD]),
    t!(CALL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x02]),
    t!(CALL, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x03]),
    t!(CALL, T_SEG_OFF, [C_BYTE, 0x9A, C_SEG_OFF]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_INT: &[Template] = &[
    t!(INT, T_IMM|T_BITS_8, [C_BYTE, 0xCD, C_IMM_BYTE]),
    t!(INT3, [C_BYTE, 0xCC]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_INTO: &[Template] = &[
    t!(INTO, [C_BYTE, 0xCE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_IRET: &[Template] = &[
    t!(IRET, [C_BYTE, 0xCF]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JB: &[Template] = &[
    t!(JB, T_IMM, [C_BYTE, 0x72, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JBE: &[Template] = &[
    t!(JBE, T_IMM, [C_BYTE, 0x76, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JCXZ: &[Template] = &[
    t!(JCXZ, T_IMM, [C_BYTE, 0xE3, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JE: &[Template] = &[
    t!(JE, T_IMM, [C_BYTE, 0x74, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JL: &[Template] = &[
    t!(JL, T_IMM, [C_BYTE, 0x7C, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JLE: &[Template] = &[
    t!(JLE, T_IMM, [C_BYTE, 0x7E, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JMP: &[Template] = &[
    t!(JMP, [C_BYTE, 0xEB, C_DISP_BYTE]),
    t!(JMP, T_IMM|T_BITS_16, [C_BYTE, 0xE9, C_DISP_WORD]),
    t!(JMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x04]),
    t!(JMP, T_REG|T_MEM_DIR|T_MEM_IND|T_BITS_16, [C_BYTE, 0xFF, C_MOD_RM, 0x05]),
    t!(JMP, T_SEG_OFF, [C_BYTE, 0xEA, C_SEG_OFF]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNB: &[Template] = &[
    t!(JNB, T_IMM, [C_BYTE, 0x73, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNBE: &[Template] = &[
    t!(JNBE, T_IMM, [C_BYTE, 0x77, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNE: &[Template] = &[
    t!(JNE, T_IMM, [C_BYTE, 0x75, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNL: &[Template] = &[
    t!(JNL, T_IMM, [C_BYTE, 0x7D, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNLE: &[Template] = &[
    t!(JNLE, T_IMM, [C_BYTE, 0x7F, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNO: &[Template] = &[
    t!(JNO, T_IMM, [C_BYTE, 0x71, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNP: &[Template] = &[
    t!(JNP, T_IMM, [C_BYTE, 0x7B, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JNS: &[Template] = &[
    t!(JNS, T_IMM, [C_BYTE, 0x79, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JO: &[Template] = &[
    t!(JO, T_IMM, [C_BYTE, 0x70, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JP: &[Template] = &[
    t!(JP, T_IMM, [C_BYTE, 0x7A, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_JS: &[Template] = &[
    t!(JS, T_IMM, [C_BYTE, 0x78, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LOOP: &[Template] = &[
    t!(LOOP, T_IMM, [C_BYTE, 0xE2, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LOOPNZ: &[Template] = &[
    t!(LOOPNZ, T_IMM, [C_BYTE, 0xE0, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LOOPZ: &[Template] = &[
    t!(LOOPZ, T_IMM, [C_BYTE, 0xE1, C_DISP_BYTE]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_RET: &[Template] = &[
    t!(RET, [C_BYTE, 0xC3]),
    t!(RET, [C_BYTE, 0xCB]),
    t!(RET, T_IMM|T_BITS_16, [C_BYTE, 0xC2, C_DISP_WORD]),
    t!(RET, T_DISP|T_BITS_16, [C_BYTE, 0xCA, C_DISP_WORD]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CLC: &[Template] = &[
    t!(CLC, [C_BYTE, 0xF8]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CLD: &[Template] = &[
    t!(CLD, [C_BYTE, 0xFC]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CLI: &[Template] = &[
    t!(CLI, [C_BYTE, 0xFA]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_CMC: &[Template] = &[
    t!(CMC, [C_BYTE, 0xF5]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_ESC: &[Template] = &[
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_HLT: &[Template] = &[
    t!(HLT, [C_BYTE, 0xF4]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_LOCK: &[Template] = &[
    t!(LOCK, [C_BYTE, 0xF0]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_NOP: &[Template] = &[
    t!(NOP, [C_BYTE, 0x90]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_STC: &[Template] = &[
    t!(STC, [C_BYTE, 0xF9]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_STD: &[Template] = &[
    t!(STD, [C_BYTE, 0xFD]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_STI: &[Template] = &[
    t!(STI, [C_BYTE, 0xFB]),
];

#[rustfmt::skip]
pub(crate) const INSTRUCTIONS_WAIT: &[Template] = &[
    t!(WAIT, [C_BYTE, 0x9B]),
];

pub const TEMPLATES: &[&[Template]] = &[
    INSTRUCTIONS_IN,
    INSTRUCTIONS_LAHF,
    INSTRUCTIONS_LDS,
    INSTRUCTIONS_LEA,
    INSTRUCTIONS_LES,
    INSTRUCTIONS_MOV,
    INSTRUCTIONS_OUT,
    INSTRUCTIONS_POP,
    INSTRUCTIONS_POPF,
    INSTRUCTIONS_PUSH,
    INSTRUCTIONS_PUSHF,
    INSTRUCTIONS_SAHF,
    INSTRUCTIONS_XCHG,
    INSTRUCTIONS_XLAT,
    INSTRUCTIONS_AAA,
    INSTRUCTIONS_AAD,
    INSTRUCTIONS_AAM,
    INSTRUCTIONS_AAS,
    INSTRUCTIONS_ADC,
    INSTRUCTIONS_ADD,
    INSTRUCTIONS_CBW,
    INSTRUCTIONS_CMP,
    INSTRUCTIONS_CWD,
    INSTRUCTIONS_DAA,
    INSTRUCTIONS_DAS,
    INSTRUCTIONS_DEC,
    INSTRUCTIONS_DIV,
    INSTRUCTIONS_IDIV,
    INSTRUCTIONS_IMUL,
    INSTRUCTIONS_INC,
    INSTRUCTIONS_MUL,
    INSTRUCTIONS_NEG,
    INSTRUCTIONS_SBB,
    INSTRUCTIONS_SUB,
    INSTRUCTIONS_AND,
    INSTRUCTIONS_NOT,
    INSTRUCTIONS_OR,
    INSTRUCTIONS_RCL,
    INSTRUCTIONS_RCR,
    INSTRUCTIONS_ROL,
    INSTRUCTIONS_ROR,
    INSTRUCTIONS_SAR,
    INSTRUCTIONS_SHL,
    INSTRUCTIONS_SHR,
    INSTRUCTIONS_TEST,
    INSTRUCTIONS_XOR,
    INSTRUCTIONS_CMPS,
    INSTRUCTIONS_LODS,
    INSTRUCTIONS_MOVS,
    INSTRUCTIONS_REP,
    INSTRUCTIONS_SCAS,
    INSTRUCTIONS_STOS,
    INSTRUCTIONS_CALL,
    INSTRUCTIONS_INT,
    INSTRUCTIONS_INTO,
    INSTRUCTIONS_IRET,
    INSTRUCTIONS_JB,
    INSTRUCTIONS_JBE,
    INSTRUCTIONS_JCXZ,
    INSTRUCTIONS_JE,
    INSTRUCTIONS_JL,
    INSTRUCTIONS_JLE,
    INSTRUCTIONS_JMP,
    INSTRUCTIONS_JNB,
    INSTRUCTIONS_JNBE,
    INSTRUCTIONS_JNE,
    INSTRUCTIONS_JNL,
    INSTRUCTIONS_JNLE,
    INSTRUCTIONS_JNO,
    INSTRUCTIONS_JNP,
    INSTRUCTIONS_JNS,
    INSTRUCTIONS_JO,
    INSTRUCTIONS_JP,
    INSTRUCTIONS_JS,
    INSTRUCTIONS_LOOP,
    INSTRUCTIONS_LOOPNZ,
    INSTRUCTIONS_LOOPZ,
    INSTRUCTIONS_RET,
    INSTRUCTIONS_CLC,
    INSTRUCTIONS_CLD,
    INSTRUCTIONS_CLI,
    INSTRUCTIONS_CMC,
    INSTRUCTIONS_ESC,
    INSTRUCTIONS_HLT,
    INSTRUCTIONS_LOCK,
    INSTRUCTIONS_NOP,
    INSTRUCTIONS_STC,
    INSTRUCTIONS_STD,
    INSTRUCTIONS_STI,
    INSTRUCTIONS_WAIT,
];
