[package]
name = "led_show"
version = "0.0.1"
edition = "2021"

[dependencies]
glium = "0.31"
image = { version = "0.24", default-features = false, features = ["png"] }
mrc_emulator = { path = "../../crates/mrc_emulator" }
png = "=0.17.3"
pretty_env_logger = "0.4"
